Header_links:
  type: list
  default: "Desktop mobile link, fab-facebook, https://facebook.com, vdm, blank|Mobile-only link, fab-twitter, https://twitter.com, vmo, blank"
  description:
    en: "Comma delimited in this order: <br>
      <b>title, icon, URL, view, target</b>
      <br>
      <br>
      <b>title</b>: the desired title you want the link to have (when hovered). <br>
      <b>icon</b>: the icon you want the link to have. <br>
      <b>URL</b>: the desired URL you want the link to point to. <br>
      <b>View</b>:
      <ul>
      <li>visible on both desktop and mobile devices (vdm)</li>
      <li>Desktop only (vdo).</li>
      <li>mobile only (vmo).</li>
      </ul>
      <b>Target</b>: same tab (self) or new tab (blank)."
add_whitespace:
  type: bool
  default: false
  description:
    en: "If checked, this will add some whitespace between the default Discourse header icons and the custom icons added via this component"
Svg_icons:
  type: "list"
  list_type: "compact"
  default: "fab-facebook|fab-twitter"
  description:
    en: "Include FontAwesome 5 icon classes for each icon used in the list."
