add_whitespace:
  type: bool
  default: false
Svg_icons:
  type: "list"
  list_type: "compact"
  default: "fab-facebook|fab-twitter"
header_links:
  type: objects
  default:
    - title: "Desktop and mobile link"
      icon: "fab-facebook"
      url: "https://facebook.com"
      view: "vdm"
      target: "blank"
    - title: "Mobile-only link"
      icon: "fab-twitter"
      url: "https://twitter.com"
      view: "vmo"
      target: "blank"
  schema:
    name: "link"
    properties:
      title:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 1000
      icon:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 2048
      url:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 2048
          url: true
      view:
        type: enum
        choices:
          - vdm
          - vdo
          - vmo
      width:
        type: integer
        required: false
      target:
        type: enum
        choices:
          - blank
          - self
